# Generated by Django 4.0.1 on 2023-01-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0010_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='capital',
            field=models.TextField(default=500000),
        ),
    ]
