# Generated by Django 4.0.1 on 2023-01-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0016_alter_userprofile_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.IntegerField(default=2),
        ),
    ]
